In this notebook I will download the data from a text file and clean it. This will include removing unnecessary columns, merging a few columns that were separated when getting the data, and adding column names.

In [1]:
#Import libraries
import numpy as np
import pandas as pd

The data set I will use is a txt document, which presents a few challenges: 
There is not a consistent delimiter, since the amount of whitespace separating variables is inconsistent.
The other challenge is that any column which contains a phrase will be broken up into multiple columns. In this dataset the column for the name of the county includes two or three words, separated by whitespace, and will have to be cleaned up.

In [19]:
#Location of data set
dataset_path = 'https://www2.census.gov/programs-surveys/saipe/datasets/2020/2020-state-and-county/est20-tx.txt'
#Since the county name column in the data set can include either 2 or 3 words (eg 'Victoria County' and 'Van Zandt County'),
#I will limit the number of columns to read to give every row the same number of columns. 
#This will cut off part of the last column in the data set, the date of data input, however this is the same date for all of the data and will not be kept in the data set that I use
#Another option would have been to limit the columns read to not include the county name at all, leaving only the FIPS code to identitfy the county

#Create list of columns to read from data set
col_list = np.arange(27)
dfSAIPE = pd.read_csv(dataset_path, 
                      delim_whitespace = True, 
                      usecols = col_list,
                      skiprows = 1, #The first row is the aggregate data for the state, which includes additional columns not found in other rows, and does not allow for a simple solution to read into a data frame
                      header = None)

As can be seen below, the county names are split between 2 or 3 columns. Below I delete the last column, modufy column 25 so that only cells with the value 'County' remain, and then merge the cells into one cell with the whole county name. See the comment in the cell above to see other ways to have handled the data set.

In [20]:
dfSAIPE.iloc[230:236]

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
230,48,461,430,319,541,12.1,9.0,15.2,174,117,...,16.0,10.6,21.4,59593,53005,66181,Upton,County,TX,est20-tx.txt
231,48,463,4984,3820,6148,19.0,14.6,23.4,2150,1501,...,29.7,20.0,39.4,49275,45416,53134,Uvalde,County,TX,est20-tx.txt
232,48,465,7332,5535,9129,15.6,11.8,19.4,3298,2131,...,25.1,16.1,34.1,54346,49564,59128,Val,Verde,County,TX
233,48,467,7302,5669,8935,12.9,10.0,15.8,2276,1546,...,17.2,11.4,23.0,57891,51132,64650,Van,Zandt,County,TX
234,48,469,14859,12540,17178,16.5,13.9,19.1,5483,4209,...,22.2,16.3,28.1,53583,48184,58982,Victoria,County,TX,est20-tx.txt
235,48,471,9987,7345,12629,18.0,13.2,22.8,2166,1433,...,20.4,13.3,27.5,43002,40278,45726,Walker,County,TX,est20-tx.txt

In [21]:
#Drop the last column which contains either the state where the county is located or the name of the file, both of which are the same for all rows in the data set
dfSAIPE.drop([26], axis = 1, inplace = True)
dfSAIPE.shape

(254, 26)

As shown below, counties with a single-word name, like Victoria County, will need to merge columns 23 and 24, while not merging the state code. Counties with a two-word name, like Van Zandt County, will need to have all three final columns merged.

In [22]:
dfSAIPE.iloc[230:236]

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
230,48,461,430,319,541,12.1,9.0,15.2,174,117,...,164,16.0,10.6,21.4,59593,53005,66181,Upton,County,TX
231,48,463,4984,3820,6148,19.0,14.6,23.4,2150,1501,...,2013,29.7,20.0,39.4,49275,45416,53134,Uvalde,County,TX
232,48,465,7332,5535,9129,15.6,11.8,19.4,3298,2131,...,3325,25.1,16.1,34.1,54346,49564,59128,Val,Verde,County
233,48,467,7302,5669,8935,12.9,10.0,15.8,2276,1546,...,2192,17.2,11.4,23.0,57891,51132,64650,Van,Zandt,County
234,48,469,14859,12540,17178,16.5,13.9,19.1,5483,4209,...,4614,22.2,16.3,28.1,53583,48184,58982,Victoria,County,TX
235,48,471,9987,7345,12629,18.0,13.2,22.8,2166,1433,...,2050,20.4,13.3,27.5,43002,40278,45726,Walker,County,TX

In [23]:
#Go through the last column of each row and replace the instances of the state code ('TX') with a null value
for row in range(len(dfSAIPE)):
    if dfSAIPE.iloc[row, 25] == 'TX':
        dfSAIPE.iloc[row, 25] = ''

In [24]:
dfSAIPE.iloc[230:236]

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
230,48,461,430,319,541,12.1,9.0,15.2,174,117,...,164,16.0,10.6,21.4,59593,53005,66181,Upton,County,
231,48,463,4984,3820,6148,19.0,14.6,23.4,2150,1501,...,2013,29.7,20.0,39.4,49275,45416,53134,Uvalde,County,
232,48,465,7332,5535,9129,15.6,11.8,19.4,3298,2131,...,3325,25.1,16.1,34.1,54346,49564,59128,Val,Verde,County
233,48,467,7302,5669,8935,12.9,10.0,15.8,2276,1546,...,2192,17.2,11.4,23.0,57891,51132,64650,Van,Zandt,County
234,48,469,14859,12540,17178,16.5,13.9,19.1,5483,4209,...,4614,22.2,16.3,28.1,53583,48184,58982,Victoria,County,
235,48,471,9987,7345,12629,18.0,13.2,22.8,2166,1433,...,2050,20.4,13.3,27.5,43002,40278,45726,Walker,County,

In [25]:
#Merge final three columns into one 'County' column
dfSAIPE['CountyName'] = dfSAIPE[23] + ' ' + dfSAIPE[24] + ' ' + dfSAIPE[25]
dfSAIPE.iloc[230:236]

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,CountyName
230,48,461,430,319,541,12.1,9.0,15.2,174,117,...,16.0,10.6,21.4,59593,53005,66181,Upton,County,,Upton County
231,48,463,4984,3820,6148,19.0,14.6,23.4,2150,1501,...,29.7,20.0,39.4,49275,45416,53134,Uvalde,County,,Uvalde County
232,48,465,7332,5535,9129,15.6,11.8,19.4,3298,2131,...,25.1,16.1,34.1,54346,49564,59128,Val,Verde,County,Val Verde County
233,48,467,7302,5669,8935,12.9,10.0,15.8,2276,1546,...,17.2,11.4,23.0,57891,51132,64650,Van,Zandt,County,Van Zandt County
234,48,469,14859,12540,17178,16.5,13.9,19.1,5483,4209,...,22.2,16.3,28.1,53583,48184,58982,Victoria,County,,Victoria County
235,48,471,9987,7345,12629,18.0,13.2,22.8,2166,1433,...,20.4,13.3,27.5,43002,40278,45726,Walker,County,,Walker County

In [26]:
#Use this next line if whitespace remains to the left or right of the county name
#dfSAIPE['CountyName'].str.strip()

In [27]:
#Drop the three columns which were combined to form the County Name column
dfSAIPE.drop([23, 24, 25], axis = 1, inplace = True)
dfSAIPE.iloc[230:236]

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,CountyName
230,48,461,430,319,541,12.1,9.0,15.2,174,117,...,123,82,164,16.0,10.6,21.4,59593,53005,66181,Upton County
231,48,463,4984,3820,6148,19.0,14.6,23.4,2150,1501,...,1518,1023,2013,29.7,20.0,39.4,49275,45416,53134,Uvalde County
232,48,465,7332,5535,9129,15.6,11.8,19.4,3298,2131,...,2445,1565,3325,25.1,16.1,34.1,54346,49564,59128,Val Verde County
233,48,467,7302,5669,8935,12.9,10.0,15.8,2276,1546,...,1636,1080,2192,17.2,11.4,23.0,57891,51132,64650,Van Zandt County
234,48,469,14859,12540,17178,16.5,13.9,19.1,5483,4209,...,3640,2666,4614,22.2,16.3,28.1,53583,48184,58982,Victoria County
235,48,471,9987,7345,12629,18.0,13.2,22.8,2166,1433,...,1520,990,2050,20.4,13.3,27.5,43002,40278,45726,Walker County

Next, to give all of the columns names. The names of the columns were adapted from https://www2.census.gov/programs-surveys/saipe/technical-documentation/file-layouts/state-county/2020-estimate-layout.txt
After the first two columns, which are the FIPS codes for the state and county, 3 measures of poverty are given for each county, expressed as both a number of people and a percentage of the population. Each measure also includes the upper and lower 90% confidence bounds. Finally there are columns for the Median Household Income along with its confidence interval bounds.

In [28]:
col_names = ['FIPS_State', 'FIPS_County', 
             'NumAllAge', 'NumAllAge90%lb', 'NumAllAge90%ub', 'PercentAllAge', 'PercentAllAge90%lb', 'PercentAllAge90%ub', 
             'Num0-17_', 'Num0-17_90%lb', 'Num0-17_90%ub', 'Percent0-17_', 'Percent0-17_90%lb', 'Percent0-17_90%ub',
             'NumRelCh5-17_', 'NumRelCh5-17_90%lb', 'NumRelCh5-17_90%ub', 'PercentRelCh5-17_', 'PercentRelCh5-17_90%lb', 'PercentRelCh5-17_90%ub',
             'MedHouseInc', 'MedHouseInc90%lb', 'MedHouseInc90%ub',
             'County_Name'
            ]
dfSAIPE.columns = col_names
dfSAIPE.head()

,FIPS_State,FIPS_County,NumAllAge,NumAllAge90%lb,NumAllAge90%ub,PercentAllAge,PercentAllAge90%lb,PercentAllAge90%ub,Num0-17_,Num0-17_90%lb,...,NumRelCh5-17_,NumRelCh5-17_90%lb,NumRelCh5-17_90%ub,PercentRelCh5-17_,PercentRelCh5-17_90%lb,PercentRelCh5-17_90%ub,MedHouseInc,MedHouseInc90%lb,MedHouseInc90%ub,County_Name
0,48,1,9242,7240,11244,20.9,16.4,25.4,2989,2331,...,2155,1696,2614,27.5,21.6,33.4,50879,45179,56579,Anderson County
1,48,3,1722,1279,2165,9.2,6.8,11.6,702,471,...,481,315,647,11.3,7.4,15.2,76600,65269,87931,Andrews County
2,48,5,14330,11468,17192,17.0,13.6,20.4,5446,4065,...,3871,2852,4890,24.2,17.8,30.6,49943,44981,54905,Angelina County
3,48,7,3986,3012,4960,17.1,12.9,21.3,1295,901,...,928,638,1218,30.6,21.0,40.2,51461,44220,58702,Aransas County
4,48,9,596,413,779,6.9,4.8,9.0,207,138,...,152,99,205,10.9,7.1,14.7,69566,60520,78612,Archer County

In [29]:
#Add leading zeros to the county FIPS number to allow for mapping of data
dfSAIPE['FIPS_County'] = dfSAIPE['FIPS_County'].apply('{:0>3}'.format)

The data set is now ready to use. Next I will save it and use it in other notebooks.

In [31]:
csv_path = 'TexasSAIPE.csv'
dfSAIPE.to_csv(csv_path)